/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation;

import java.awt.Color;

/**
 *
 * @author roberto
 */
public class VistaLoginRegistre extends javax.swing.JFrame {

    private CtrlPresentacio ctrlPresentacio;
    
    private boolean modeRegistre;
    
    /**
     * Creates new form VistaLoginRegistreNew
     */
    public VistaLoginRegistre(CtrlPresentacio ctrlPresentacio) {
        this.ctrlPresentacio = ctrlPresentacio;
        initComponents();
        
        this.modeRegistre = false;
        this.regPanel.setVisible(false);
    }
    
    private void infoMsg(String msg)
    {
        msgLabel.setText(msg);
        msgLabel.setForeground(new Color(3, 107, 46));
        msgLabel.setVisible(true);
    }
    
    private void errorMsg(String msg)
    {
        msgLabel.setText(msg);
        msgLabel.setForeground(Color.RED);
        msgLabel.setVisible(true);
    }
    
    private static boolean isNullOrEmpty(String s)
    {
        return s.isBlank() || s.isEmpty();
    }
    
    private void login()
    {
        String nomUsuari = nameField.getText();
        String password = new String(passField.getPassword());
        
        if (isNullOrEmpty(nomUsuari) || isNullOrEmpty(password)) {
            errorMsg("ERROR: S'ha d'introduir usuari i contrasenya");
            return;
        }
        
        try {
            int output = ctrlPresentacio.loginUsuari(nomUsuari, password);
            if (output == 0) {
                ctrlPresentacio.vistaPrincipal();
                dispose();
            }
            else if (output == -1) errorMsg("ERROR: L'usari amb el nom introduit no està registrat");
            else errorMsg("ERROR: La contrasenya introduida és incorrecta");
        }
        catch (Exception ex) {
            errorMsg("ERROR: desconegut");
        }
    }
    
    private void registre()
    {
        String nomUsuari = nameField.getText();
        String password = new String(passField.getPassword());
        String passwordConf = new String(passConfField.getPassword());
        
        if (isNullOrEmpty(nomUsuari) || isNullOrEmpty(password) || isNullOrEmpty(passwordConf)) {
            errorMsg("ERROR: S'ha d'introduir usuari i contrasenya");
            return;
        }
        
        try {
            int output = ctrlPresentacio.registarUsuari(nomUsuari, password, passwordConf);
            if (output == 0) {
                nameField.setText("");
                passField.setText("");
                passConfField.setText("");
                
                infoMsg("Registrat correctament");
                
                modeRegistre = false;
                regBtn.setText("Mode registre");
                loginBtn.setText("Inicia");
                regPanel.setVisible(false);
                titleLabel.setText("Iniciar sessió");
            }
            else if (output == -1) errorMsg("ERROR: El nom indicat ja està utilitzat");
            else errorMsg("ERROR: La contrasenya no coincideix amb la seva confirmació");
        }
        catch (Exception ex) {
            errorMsg("ERROR: Desconegut");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        commonPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        msgLabel = new javax.swing.JLabel();
        regBtn = new javax.swing.JButton();
        regPanel = new javax.swing.JPanel();
        passConfLabel = new javax.swing.JLabel();
        passConfField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        titleLabel.setText("Iniciar sessió");

        nameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        nameLabel.setText("Nom d'usuari");

        passLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        passLabel.setText("Contrasenya");

        javax.swing.GroupLayout commonPanelLayout = new javax.swing.GroupLayout(commonPanel);
        commonPanel.setLayout(commonPanelLayout);
        commonPanelLayout.setHorizontalGroup(
            commonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(commonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addComponent(passLabel))
                .addGap(75, 75, 75)
                .addGroup(commonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passField, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(nameField))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        commonPanelLayout.setVerticalGroup(
            commonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(commonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(commonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLabel)
                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        commonPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {nameField, nameLabel});

        loginBtn.setText("Inicia");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        regBtn.setText("Mode registre");
        regBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtnActionPerformed(evt);
            }
        });

        passConfLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        passConfLabel.setText("Confirma contrasenya");

        javax.swing.GroupLayout regPanelLayout = new javax.swing.GroupLayout(regPanel);
        regPanel.setLayout(regPanelLayout);
        regPanelLayout.setHorizontalGroup(
            regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(passConfLabel)
                .addGap(18, 18, 18)
                .addComponent(passConfField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        regPanelLayout.setVerticalGroup(
            regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passConfLabel)
                    .addComponent(passConfField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        regPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {passConfField, passConfLabel});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(regBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(commonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(msgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(regPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(commonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(regPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(msgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regBtn)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        if (modeRegistre)
            registre();
        else
            login();
    }//GEN-LAST:event_loginBtnActionPerformed

    private void regBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtnActionPerformed
        if (modeRegistre) {
            modeRegistre = false;
            regBtn.setText("Mode registre");
            loginBtn.setText("Inicia");
            titleLabel.setText("Iniciar sessió");
            regPanel.setVisible(false);
        }
        else {
            modeRegistre = true;
            regBtn.setText("Mode login");
            loginBtn.setText("Registra't");
            titleLabel.setText("Registrar-se");
            regPanel.setVisible(true);
        }
    }//GEN-LAST:event_regBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel commonPanel;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField passConfField;
    private javax.swing.JLabel passConfLabel;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JButton regBtn;
    private javax.swing.JPanel regPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
