/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation;

import java.awt.Color;
import java.io.File;
import java.util.HashMap;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JTextField;

/**
 *
 * @author roberto
 */
public class VistaPrincipalAdmin extends javax.swing.JFrame {

    private CtrlPresentacio ctrlPresentacio;
    
    private HashMap<String, Integer> mUsuaris;
    
    /**
     * Creates new form VistaPrincipalAdmin
     */
    public VistaPrincipalAdmin(CtrlPresentacio ctrlPresentacio) {
        this.ctrlPresentacio = ctrlPresentacio;
        initComponents();
        initCombo();
        initComboUsuaris();
        
        this.loadDataSetField.setColumns(10);
        this.saveDataSetField.setColumns(10);
        this.avalField.setColumns(10);
        this.msgLabel.setVisible(false);
    }
    
    private void initCombo()
    {
        List<String> tipusItems = ctrlPresentacio.getNomTipusItem();
        for (String tipus : tipusItems)
            this.tipusItemsCombo.addItem(tipus);
        
        if (tipusItems.isEmpty()) {
           itemsBtn.setEnabled(false);
           tipusItemsCombo.setEnabled(false);
        }
    }
    
    private void initComboUsuaris()
    {
        this.usersCombo.removeAllItems();
        
        mUsuaris = ctrlPresentacio.getUsuaris();
        for (String usuari : mUsuaris.keySet())
            this.usersCombo.addItem(usuari);
        
        if (mUsuaris.isEmpty()) {
           delUserBtn.setEnabled(false);
           usersCombo.setEnabled(false);
        }
    }
    
    private void infoMsg(String msg)
    {
        msgLabel.setText(msg);
        msgLabel.setForeground(new Color(3, 107, 46));
        msgLabel.setVisible(true);
    }
    
    private void errorMsg(String msg)
    {
        msgLabel.setText(msg);
        msgLabel.setForeground(Color.RED);
        msgLabel.setVisible(true);
    }
    
    private void handleFile(JTextField dest, boolean open)
    {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));
        
        int result = open ? fileChooser.showOpenDialog(this) : fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            dest.setText(selectedFile.getAbsolutePath());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutBtn = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        btnPanel = new javax.swing.JPanel();
        tipusItemBtn = new javax.swing.JButton();
        itemsBtn = new javax.swing.JButton();
        tipusItemsCombo = new javax.swing.JComboBox<>();
        usersCombo = new javax.swing.JComboBox<>();
        delUserBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        filePanel = new javax.swing.JPanel();
        loadDataSetLabel = new javax.swing.JLabel();
        loadDataSetField = new javax.swing.JTextField();
        searchLoadDataSetBtn = new javax.swing.JButton();
        LoadDataSetBtn = new javax.swing.JButton();
        saveDataSetLabel = new javax.swing.JLabel();
        saveDataSetField = new javax.swing.JTextField();
        searchSaveDataSetBtn = new javax.swing.JButton();
        saveDataSetBtn = new javax.swing.JButton();
        avalLabel = new javax.swing.JLabel();
        avalField = new javax.swing.JTextField();
        searchAvalBtn = new javax.swing.JButton();
        avalBtn = new javax.swing.JButton();
        minValScoreField = new javax.swing.JTextField();
        maxValScoreField = new javax.swing.JTextField();
        minValLabel = new javax.swing.JLabel();
        maxValLabel = new javax.swing.JLabel();
        msgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        titleLabel.setText("Admin panel");

        tipusItemBtn.setText("Gestionar tipus de ítems");
        tipusItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipusItemBtnActionPerformed(evt);
            }
        });

        itemsBtn.setText("Gestionar ítems");
        itemsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsBtnActionPerformed(evt);
            }
        });

        delUserBtn.setText("Esborrar usuari");
        delUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delUserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnPanelLayout = new javax.swing.GroupLayout(btnPanel);
        btnPanel.setLayout(btnPanelLayout);
        btnPanelLayout.setHorizontalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tipusItemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipusItemsCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usersCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        btnPanelLayout.setVerticalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tipusItemBtn)
                .addGap(18, 18, 18)
                .addComponent(tipusItemsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usersCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delUserBtn)
                .addContainerGap())
        );

        loadDataSetLabel.setText("Carrega dataset (ratings csv)");

        searchLoadDataSetBtn.setText("Cercar");
        searchLoadDataSetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchLoadDataSetBtnActionPerformed(evt);
            }
        });

        LoadDataSetBtn.setText("Carregar");
        LoadDataSetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadDataSetBtnActionPerformed(evt);
            }
        });

        saveDataSetLabel.setText("Guarda dataset (ratings csv)");

        searchSaveDataSetBtn.setText("Cercar");
        searchSaveDataSetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSaveDataSetBtnActionPerformed(evt);
            }
        });

        saveDataSetBtn.setText("Guardar");
        saveDataSetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDataSetBtnActionPerformed(evt);
            }
        });

        avalLabel.setText("Avalua dataset (conegut csv)");

        searchAvalBtn.setText("Cercar");
        searchAvalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAvalBtnActionPerformed(evt);
            }
        });

        avalBtn.setText("Avaluar");
        avalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avalBtnActionPerformed(evt);
            }
        });

        minValScoreField.setText("0");

        maxValScoreField.setText("5");

        minValLabel.setText("Min. val.");

        maxValLabel.setText("Max. val.");

        javax.swing.GroupLayout filePanelLayout = new javax.swing.GroupLayout(filePanel);
        filePanel.setLayout(filePanelLayout);
        filePanelLayout.setHorizontalGroup(
            filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadDataSetLabel)
                    .addComponent(saveDataSetLabel)
                    .addComponent(avalLabel))
                .addGap(43, 43, 43)
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(filePanelLayout.createSequentialGroup()
                        .addComponent(minValLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(minValScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(maxValLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxValScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loadDataSetField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveDataSetField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avalField, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(filePanelLayout.createSequentialGroup()
                        .addComponent(searchLoadDataSetBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LoadDataSetBtn))
                    .addGroup(filePanelLayout.createSequentialGroup()
                        .addComponent(searchSaveDataSetBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveDataSetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(filePanelLayout.createSequentialGroup()
                        .addComponent(searchAvalBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(avalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        filePanelLayout.setVerticalGroup(
            filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadDataSetLabel)
                    .addComponent(loadDataSetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchLoadDataSetBtn)
                    .addComponent(LoadDataSetBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minValScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxValScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minValLabel)
                    .addComponent(maxValLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(saveDataSetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveDataSetLabel)
                    .addComponent(searchSaveDataSetBtn)
                    .addComponent(saveDataSetBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(avalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avalLabel)
                    .addComponent(searchAvalBtn)
                    .addComponent(avalBtn))
                .addGap(27, 27, 27))
        );

        filePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {loadDataSetField, loadDataSetLabel});

        filePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {saveDataSetField, saveDataSetLabel});

        filePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {avalField, avalLabel});

        filePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {minValLabel, minValScoreField});

        filePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {maxValLabel, maxValScoreField});

        msgLabel.setText("dummy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(204, 218, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(logoutBtn)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(msgLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1)
                                .addComponent(filePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(titleLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(logoutBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(msgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        ctrlPresentacio.logoutUsuari();
        ctrlPresentacio.vistaLoginRegistre();
        dispose();
        
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void tipusItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipusItemBtnActionPerformed
        ctrlPresentacio.vistaGestioTipusItem();
        dispose();
    }//GEN-LAST:event_tipusItemBtnActionPerformed

    private void itemsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsBtnActionPerformed
        ctrlPresentacio.vistaGestioItems((String)tipusItemsCombo.getSelectedItem());
        dispose();
    }//GEN-LAST:event_itemsBtnActionPerformed

    private void searchLoadDataSetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchLoadDataSetBtnActionPerformed
        handleFile(this.loadDataSetField, true);
    }//GEN-LAST:event_searchLoadDataSetBtnActionPerformed

    private void LoadDataSetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadDataSetBtnActionPerformed
        String minS = this.minValScoreField.getText();
        String maxS = this.maxValScoreField.getText();
        
        if (minS.isBlank() || maxS.isBlank() || minS.isEmpty() || maxS.isEmpty()) {
            errorMsg("ERROR: S'ha de donar el valor màxim i mínim de les puntuacions");
            return;
        }
       
        int min = 0;
        int max = 0;
        
        try {
            min = Integer.parseInt(minS);
            max = Integer.parseInt(maxS);
        }
        catch (NumberFormatException e) {
            errorMsg("ERROR: els camps max y/o min no són nombres enters");
            return;
        }
        
        if (min >= max) {
            errorMsg("ERROR: min < max");
            return;
        }
        
        int result = ctrlPresentacio.carregarValoracionsCSV(this.loadDataSetField.getText(), min, max);
        if (result == 0)
            infoMsg("S'ha carregat el dataset correctament");
        else if (result == -1)
            errorMsg("ERROR: S'ha intentat carregar un item no donat d'alta");
        else 
            errorMsg("ERROR: Error d'entrada/sortida");
    }//GEN-LAST:event_LoadDataSetBtnActionPerformed

    private void searchSaveDataSetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSaveDataSetBtnActionPerformed
        handleFile(this.saveDataSetField, false);
    }//GEN-LAST:event_searchSaveDataSetBtnActionPerformed

    private void saveDataSetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDataSetBtnActionPerformed
        int result = ctrlPresentacio.guardarValoracionsCSV(this.saveDataSetField.getText());
        if (result == 0)
            infoMsg("S'ha guardat el fitxer correctament");
        else 
            errorMsg("ERROR: Error d'entrada/sortida");
    }//GEN-LAST:event_saveDataSetBtnActionPerformed

    private void searchAvalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAvalBtnActionPerformed
        handleFile(this.avalField, true);
    }//GEN-LAST:event_searchAvalBtnActionPerformed

    private void avalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avalBtnActionPerformed
        int result = ctrlPresentacio.avaluarRecomanacions(this.avalField.getText());
        if (result == 0)
            infoMsg("Avaluacio a: " + System.getProperty("user.dir") + "/DATA/avaluacio.csv");
        else 
            errorMsg("ERROR: Error desconegut avaluant les recomanacions");
    }//GEN-LAST:event_avalBtnActionPerformed

    private void delUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delUserBtnActionPerformed
        String usuari = (String)this.usersCombo.getSelectedItem();
        int idUsuari = mUsuaris.get(usuari);
        int result = ctrlPresentacio.eliminarUsuari(idUsuari);
        
        if (result == 0) {
            infoMsg("S'ha esborrat l'usuari correctament");
            initComboUsuaris();
        }
        else if (result == -3) errorMsg("ERROR: No s'ha pogut trobar un usuari amb el id especificat");
        else if (result == -4) errorMsg("ERROR: No es pot esborrar l'usuari actiu");
        else errorMsg("ERROR: desconegut");
    }//GEN-LAST:event_delUserBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoadDataSetBtn;
    private javax.swing.JButton avalBtn;
    private javax.swing.JTextField avalField;
    private javax.swing.JLabel avalLabel;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton delUserBtn;
    private javax.swing.JPanel filePanel;
    private javax.swing.JButton itemsBtn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField loadDataSetField;
    private javax.swing.JLabel loadDataSetLabel;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel maxValLabel;
    private javax.swing.JTextField maxValScoreField;
    private javax.swing.JLabel minValLabel;
    private javax.swing.JTextField minValScoreField;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JButton saveDataSetBtn;
    private javax.swing.JTextField saveDataSetField;
    private javax.swing.JLabel saveDataSetLabel;
    private javax.swing.JButton searchAvalBtn;
    private javax.swing.JButton searchLoadDataSetBtn;
    private javax.swing.JButton searchSaveDataSetBtn;
    private javax.swing.JButton tipusItemBtn;
    private javax.swing.JComboBox<String> tipusItemsCombo;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JComboBox<String> usersCombo;
    // End of variables declaration//GEN-END:variables
}
