/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation;

import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author yoqkn
 */
public class VistaGestioTipusItem extends javax.swing.JFrame {
    private DefaultListModel tipusitem;
    private DefaultListModel tipusatributs;
    CtrlPresentacio ctrlPresentacio;
    /**
     * Creates new form VistaGestioTipusItem
     */
    public VistaGestioTipusItem(CtrlPresentacio ctrlPresentacio) {
        this.ctrlPresentacio = ctrlPresentacio;
        initComponents();
        
        this.tipusitem = new DefaultListModel();
        this.tipusatributs = new DefaultListModel();

        List<String> nomTipusItem = ctrlPresentacio.getNomTipusItem();
        for (String nomTipus: nomTipusItem) {
            tipusitem.addElement(nomTipus);
        }
        listTipusItem.setModel(tipusitem);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTipusItem = new javax.swing.JList<>();
        btEliminarTipusItem = new javax.swing.JButton();
        btModificarTipusItem = new javax.swing.JButton();
        btCrearTipusItem = new javax.swing.JButton();
        txtNomTipusItem = new javax.swing.JTextField();
        labelInfo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Noto Sans CJK TC Light", 1, 24)); // NOI18N
        jLabel1.setText("Tipus Item");

        listTipusItem.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listTipusItem.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listTipusItemValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listTipusItem);

        btEliminarTipusItem.setText("Eliminar tipus item");
        btEliminarTipusItem.setEnabled(false);
        btEliminarTipusItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarTipusItemActionPerformed(evt);
            }
        });

        btModificarTipusItem.setText("Modificar tipus item");
        btModificarTipusItem.setEnabled(false);
        btModificarTipusItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarTipusItemActionPerformed(evt);
            }
        });

        btCrearTipusItem.setText("Crear tipus item");
        btCrearTipusItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearTipusItemActionPerformed(evt);
            }
        });

        txtNomTipusItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomTipusItemActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Noto Sans CJK TC Light", 1, 15)); // NOI18N
        jLabel3.setText("Nom tipus item:");

        exitBtn.setText("Sortir");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                        .addComponent(btEliminarTipusItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btModificarTipusItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exitBtn))
                        .addComponent(labelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                        .addComponent(btCrearTipusItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNomTipusItem))
                    .addComponent(jLabel3))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(exitBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomTipusItem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btCrearTipusItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btModificarTipusItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEliminarTipusItem)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btEliminarTipusItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarTipusItemActionPerformed
        if (txtNomTipusItem.getText().length() == 0) labelInfo.setText("Seleccioneu o introduiu el tipus d'item que voleu eliminiar");
        int retVal = ctrlPresentacio.eliminarTipusItem(txtNomTipusItem.getText());
        if (retVal == -1) labelInfo.setText("El tipus d'item introduit no existeix");
        else if (retVal == -2) labelInfo.setText("Existeix item en el tipus d'item introduit");
        else labelInfo.setText("El tipus d'item introduit s'ha eliminat correctament");
        tipusitem.removeElement(txtNomTipusItem.getText());
        listTipusItem.setModel(tipusitem);
        txtNomTipusItem.setText("");
    }//GEN-LAST:event_btEliminarTipusItemActionPerformed

    private void btModificarTipusItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarTipusItemActionPerformed
        // TODO add your handling code here:
        if (txtNomTipusItem.getText().length() == 0) labelInfo.setText("Seleccioneu o introduiu el tipus d'item que voleu eliminiar");
        ctrlPresentacio.vistaGestioTipusAtribut(txtNomTipusItem.getText());
    }//GEN-LAST:event_btModificarTipusItemActionPerformed

    private void btCrearTipusItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearTipusItemActionPerformed
        if (txtNomTipusItem.getText().isBlank() || txtNomTipusItem.getText().isEmpty()) {
            labelInfo.setText("Introduiu el tipus d'ítem que voleu crear (no buit)");
            return;
        }
        int retVal = ctrlPresentacio.crearTipusItem(txtNomTipusItem.getText());
        if (retVal == 0) {
            labelInfo.setText("El tipus d'item s'ha creat correctament");
            tipusitem.addElement(txtNomTipusItem.getText());        
        }
        else labelInfo.setText("El tipus d'item introduit ja existeix");
        txtNomTipusItem.setText("");
    }//GEN-LAST:event_btCrearTipusItemActionPerformed

    private void txtNomTipusItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomTipusItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomTipusItemActionPerformed

    private void listTipusItemValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listTipusItemValueChanged
        List<String> l = listTipusItem.getSelectedValuesList();
        
        boolean selected = l.size() > 0;
        
        btCrearTipusItem.setEnabled(!selected);
        btEliminarTipusItem.setEnabled(selected);
        btModificarTipusItem.setEnabled(selected);
        txtNomTipusItem.setEnabled(!selected);
        
        txtNomTipusItem.setText(selected ? l.get(0) : "");
    }//GEN-LAST:event_listTipusItemValueChanged

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        ctrlPresentacio.vistaPrincipal();
        dispose();
    }//GEN-LAST:event_exitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCrearTipusItem;
    private javax.swing.JButton btEliminarTipusItem;
    private javax.swing.JButton btModificarTipusItem;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JList<String> listTipusItem;
    private javax.swing.JTextField txtNomTipusItem;
    // End of variables declaration//GEN-END:variables
}
